import { notFound } from 'next/navigation'
import Link from 'next/link'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { ArrowLeft, Clock, ChevronLeft, ChevronRight } from 'lucide-react'
import { getLanguageBySlug, getCategoryTopics, getTopicBySlug, ApiException } from '@/lib/api'
import { MarkdownRenderer } from '@/components/content/MarkdownRenderer'
import { TableOfContents } from '@/components/content/TableOfContents'
import { ProgressBar } from '@/components/content/ProgressBar'
import { TopicList } from '@/components/content/TopicList'
import { RelatedQuestions } from '@/components/interview/RelatedQuestions'

export default async function TopicPage({
  params,
}: {
  params: Promise<{ slug: string; category: string; topic: string }>
}) {
  const { slug, category: categorySlug, topic: topicSlug } = await params

  let languageData;
  let categoryData;
  let topic;

  try {
    // Fetch language, category, and topic in parallel
    [languageData, categoryData, topic] = await Promise.all([
      getLanguageBySlug(slug),
      getCategoryTopics(slug, categorySlug),
      getTopicBySlug(slug, categorySlug, topicSlug),
    ]);
  } catch (err) {
    if (err instanceof ApiException && err.statusCode === 404) {
      notFound()
    }
    throw err;
  }

  const language = languageData;
  const category = categoryData;
  const allTopics = categoryData.topics.filter(t => t.is_published);

  // If topic has no content yet, show a message
  if (!topic.content) {
    return (
      <div className="container max-w-4xl mx-auto px-4 py-12">
        <Link href={`/learn/${slug}/${categorySlug}`}>
          <Button variant="ghost" className="mb-6">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to {category.name}
          </Button>
        </Link>
        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-8 text-center">
          <h1 className="text-2xl font-bold text-gray-900 mb-4">{topic.title}</h1>
          <p className="text-lg text-gray-600 mb-2">
            This content is currently being generated by our AI system.
          </p>
          <p className="text-sm text-gray-500">
            Check back soon! We're creating high-quality, in-depth tutorials for you.
          </p>
        </div>
      </div>
    );
  }

  // Find previous and next topics
  const currentIndex = allTopics.findIndex(t => t.id === topic.id)
  const previousTopic = currentIndex > 0 ? allTopics[currentIndex - 1] : null
  const nextTopic = currentIndex < allTopics.length - 1 ? allTopics[currentIndex + 1] : null

  // Related topics (same difficulty or category)
  const relatedTopics = allTopics
    .filter(t => t.id !== topic.id && t.difficulty === topic.difficulty && t.content)
    .slice(0, 3)

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="container max-w-7xl mx-auto px-4 py-12">
        {/* Breadcrumb Navigation */}
        <nav className="flex items-center gap-2 text-sm text-gray-600 mb-6">
          <Link href="/learn" className="hover:text-blue-600">
            Learn
          </Link>
          <span>/</span>
          <Link href={`/learn/${slug}`} className="hover:text-blue-600">
            {language.name}
          </Link>
          <span>/</span>
          <Link href={`/learn/${slug}/${categorySlug}`} className="hover:text-blue-600">
            {category.name}
          </Link>
          <span>/</span>
          <span className="text-gray-900 font-medium">{topic.title}</span>
        </nav>

        <div className="grid lg:grid-cols-[1fr_300px] gap-8">
          {/* Main Content */}
          <div className="space-y-6 min-w-0">
            {/* Topic Header */}
            <div className="bg-white rounded-lg border border-gray-200 p-8">
              <h1 className="text-4xl font-bold text-gray-900 mb-4">{topic.title}</h1>
              <div className="flex items-center gap-4 text-sm text-gray-600">
                <Badge
                  variant={
                    topic.difficulty === 'beginner'
                      ? 'default'
                      : topic.difficulty === 'intermediate'
                      ? 'secondary'
                      : 'outline'
                  }
                >
                  {topic.difficulty}
                </Badge>
                <span className="flex items-center gap-1">
                  <Clock className="w-4 h-4" />
                  {topic.estimated_read_time || 10} min read
                </span>
                {topic.prerequisites && topic.prerequisites.length > 0 && (
                  <div className="flex items-center gap-1">
                    <Badge variant="outline" className="text-xs">
                      Prerequisites: {topic.prerequisites.join(', ')}
                    </Badge>
                  </div>
                )}
              </div>
            </div>

            {/* Markdown Content */}
            <MarkdownRenderer content={topic.content} />

            {/* Navigation Buttons */}
            <div className="flex items-center justify-between gap-4">
              {previousTopic ? (
                <Link
                  href={`/learn/${slug}/${categorySlug}/${previousTopic.slug}`}
                  className="flex-1"
                >
                  <Button variant="outline" className="w-full justify-start">
                    <ChevronLeft className="w-4 h-4 mr-2" />
                    <div className="text-left">
                      <div className="text-xs text-gray-500">Previous</div>
                      <div className="text-sm font-medium truncate">{previousTopic.title}</div>
                    </div>
                  </Button>
                </Link>
              ) : (
                <div className="flex-1" />
              )}

              {nextTopic ? (
                <Link
                  href={`/learn/${slug}/${categorySlug}/${nextTopic.slug}`}
                  className="flex-1"
                >
                  <Button variant="outline" className="w-full justify-end">
                    <div className="text-right">
                      <div className="text-xs text-gray-500">Next</div>
                      <div className="text-sm font-medium truncate">{nextTopic.title}</div>
                    </div>
                    <ChevronRight className="w-4 h-4 ml-2" />
                  </Button>
                </Link>
              ) : (
                <div className="flex-1" />
              )}
            </div>

            {/* Back to Category Button */}
            <Link href={`/learn/${slug}/${categorySlug}`}>
              <Button variant="ghost" className="w-full">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back to {category.name}
              </Button>
            </Link>
          </div>

          {/* Sidebar */}
          <div className="space-y-6">
            {/* Table of Contents */}
            <TableOfContents content={topic.content} />

            {/* Progress Card */}
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Your Progress</CardTitle>
              </CardHeader>
              <CardContent>
                <ProgressBar
                  current={currentIndex + 1}
                  total={allTopics.length}
                  label="Topic"
                  showPercentage={true}
                />
              </CardContent>
            </Card>

            {/* Related Interview Questions */}
            <RelatedQuestions
              topicId={topic.id}
              topicTitle={topic.title}
              maxQuestions={5}
            />

            {/* Related Topics */}
            {relatedTopics.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg">Related Topics</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {relatedTopics.map(relatedTopic => (
                      <Link
                        key={relatedTopic.id}
                        href={`/learn/${slug}/${categorySlug}/${relatedTopic.slug}`}
                        className="block p-3 rounded-lg border border-gray-200 hover:bg-gray-50 transition-colors"
                      >
                        <div className="text-sm font-medium text-gray-900 mb-1">
                          {relatedTopic.title}
                        </div>
                        <div className="flex items-center gap-2 text-xs text-gray-500">
                          <Badge variant="secondary" className="text-xs">
                            {relatedTopic.difficulty}
                          </Badge>
                          <span className="flex items-center gap-1">
                            <Clock className="w-3 h-3" />
                            {relatedTopic.estimated_read_time || 10}min
                          </span>
                        </div>
                      </Link>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}

            {/* All Topics in Category */}
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">{category.name} Topics</CardTitle>
              </CardHeader>
              <CardContent className="p-4">
                <TopicList
                  topics={allTopics}
                  languageSlug={slug}
                  categorySlug={categorySlug}
                  currentTopicId={topic.id}
                  showProgress={false}
                />
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  )
}
